name: Docker Build and Push

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  Docker_CICD_Pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t buildandpackage:latest .

      - name: Run Docker container
        run: docker run --rm buildandpackage:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag image
        run: |
          docker tag buildandpackage:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/buildandpackage:latest

      - name: Push image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/buildandpackage:latest